export default {
  MOVIES: "MOVIES",
  CURRENT_PAGE: "CURRENT_PAGE",
  TOGGLE_LOADER: "TOGGLE_LOADER",
  REMOVE_MOVIE: "REMOVE_MOVIE",
  ISSEARCH: "ISSEARCH",
  SHOW_TOAST_NOTYFY: "SHOW_TOAST_NOTYFY",
}